# Generated by Django 5.0.7 on 2024-07-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="community_post",
            new_name="CommunityPost",
        ),
        migrations.RenameModel(
            old_name="create_community_model",
            new_name="CreateCommunity",
        ),
        migrations.RenameModel(
            old_name="post_command",
            new_name="PostCommand",
        ),
    ]
