# Generated by Django 5.0.7 on 2024-07-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp",
            "0002_rename_community_post_communitypost_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="createcommunity",
            name="community_type",
        ),
        migrations.AlterField(
            model_name="createcommunity",
            name="community_profile",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="community_profile",
            ),
        ),
    ]
