# Generated by Django 5.0.7 on 2024-07-30 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_community_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypost",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community",
                to="myapp.community",
            ),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="is_likes",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
            ),
        ),
    ]
