# Generated by Django 5.0.7 on 2024-07-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_communitypost_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="communitypost",
            old_name="count",
            new_name="counts",
        ),
    ]
