# Generated by Django 5.0.7 on 2024-07-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_rename_count_communitypost_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="communitypost",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
